# Site settings
title: "Resume-KIM"
description: "Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Woojung Kim, Ph.D."
resume_title:                   "Assistant Professor at the Graduate School of Logistics at the Incheon National University"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "[TBA]"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "[TBA]"
resume_contact_address:         "[TBA]"

resume_header_contact_info:     "119 Academy-ro, Yeonsu-gu, Incheon, Republic of Korea 22012 • wkim@inu.ac.kr"
display_header_contact_info:    "true"

resume_header_intro: "<p>Woojung Kim joined the Graduate School of Logistics at the Incheon National University (INU GSL) as an assistant professor in spring 2023. He holds a doctoral degree in transportation engineering from Rensselaer Polytechnic Institute in Troy, NY. Prior to joining INU GSL, he worked for Virginia Tech, Washington DC Government, Rensselaer Polytechnic Institute, and Seoul National University. His research primarily focuses on urban freight systems and has been published in prestigious journals such as Transportation Research Part A, Part C, and Transportation. He has been involved in various research projects funded by the National Cooperative Highway Research Program (NCHRP), the U.S. Department of Energy, and the District Department of Transportation among others. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
#resume_social_links:
#  resume_github_url:            "https://github.com/jglovier/resume-template"
#  resume_twitter_url:           "http://twitter.com/jglovier"
#  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
#  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
#  resume_website_url:           "http://joelglovier.com"
#  resume_medium_url:            "https://medium.com/@jglovier"
#resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
